apiVersion: v1
kind: Service
metadata:
  name: kube-state-nodeport
  namespace: kube-state
spec:
  selector:
    app.kubernetes.io/name: kube-state-metrics
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30002

