apiVersion: v1
kind: Service
metadata:
  name: argocd-server-lb
  namespace: argocd
  labels:
    name: argocd-server-lb
  # Optional: pin a specific MetalLB IP from your pool
  # annotations:
  #   metallb.universe.tf/loadBalancerIPs: "X.X.X.X"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app.kubernetes.io/name: argocd-server
  ports:
    - name: https
      port: 443
      targetPort: 8080
      protocol: TCP
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
