apiVersion: apps/v1
kind: Deployment
metadata:
  name: depolyment01
  labels:
    name: deployment-label01
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
