apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mygninx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: mygninx
    spec:
      containers:
      - name: nginx-container
        image: nginx:alpine
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /liveness-check
            port: 80
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
          periodSeconds: 10
