apiVersion: v1
kind: Service
metadata:
  name: mysql-headless-service
spec:
  clusterIP: None
  selector:
    app: mysql-statefulset
  ports:
    - port: 3306


---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-app-01
  labels:
    app: mysqlApp
spec:
  replicas: 5
  selector:
    matchLabels:
      app: mysql-template
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: mysql-template
    spec:
      containers:
        - name: mysql-container
          image: mysql:lts
          imagePullPolicy: IfNotPresent
          ports:
            -  containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: artmiss
