apiVersion: v1
kind: Pod
metadata:
  name: busybox-pod
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sh", "-c", "echo $MYVAR && sleep 3600"]
      env:
        - name: MYVAR
          valueFrom:
            configMapKeyRef:
              name: myconfigmap 
              key: MYVAR
