apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: devops
  labels:
    app: nginx
spec:
  volumes:
  - name: nginx-config
    configMap:
      name: myconfig2

  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 80
    volumeMounts:
    - name: nginx-config
      mountPath: /etc/nginx/conf.d/default.conf
      subPath: nginx.conf
    - name: nginx-config
      mountPath: /usr/share/nginx/html/index.html
      subPath: index.html

