apiVersion: v1
kind: Pod
metadata:
  name: app1
  labels: 
    app: devops-app
    server: serverx

spec:
  containers:
    - name: nginx-container
      image: nginx:alpine
      ports:
        - containerPort: 80
          protocol: TCP
