apiVersion: v1
kind: Pod
metadata:
  name: init-container-pod
  labels:
    app: nginx-ip-server
spec:
  initContainers:
    - name: ip-writer-container
      image: busybox
      command: ['sh', '-c', 'echo $POD_IP > /shared-volume-on-first-container/pod_ip.txt']
      env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
      volumeMounts:
        - name: my-volume
          mountPath: /shared-volume-on-first-container

    - name: home-page-generator-containor
      image: busybox
      command: ['sh', '-c', 'echo "Hello There! Welcome to $(cat /shared-volume-on-second-container/pod_ip.txt)" > /home-page-index/index.html']
      volumeMounts:
        - name: my-volume
          mountPath: /shared-volume-on-second-container
        - name: index-files
          mountPath: /home-page-index

  containers:
    - name: nginx-webserver
      image: nginx:alpine
      ports:
        - containerPort: 80
          protocol: TCP
      volumeMounts:
        - name: index-files
          mountPath: /usr/share/nginx/html

  volumes:
    - name: my-volume
      emptyDir: {}
    - name: index-files
      emptyDir: {}
