apiVersion: v1
kind: Service
metadata:
  name: nginx-headless-service
spec:
  clusterIP: None
  selector:
    app: nginx-app-headless
  ports:
    - port: 80


---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-app-01
  labels:
    app: nginx-statefulset
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-app-headless
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        app: nginx-app-headless
    spec:
      containers:
        - name: nginx-container
          image: nginx:alpine
          ports:
            -  containerPort: 80
